Update address-sanitizer.yml

diff --git a/.github/workflows/address-sanitizer.yml b/.github/workflows/address-sanitizer.yml
--- a/.github/workflows/address-sanitizer.yml
+++ b/.github/workflows/address-sanitizer.yml
@@ -64,20 +64,27 @@ jobs:
           export PREFIX=$PWD
           export LD_LIBRARY_PATH=$PREFIX/lib
           nohup ./bin/rtrouted -f -l DEBUG > /tmp/rtrouted_log.txt &
-      - name: Run RbusTestTimeoutValues Unit test
+      - name: Run Gtest Cases
         run: |
-          cd install/usr
-          export PREFIX=$PWD
-          export LD_LIBRARY_PATH=$PREFIX/lib
-          export ASAN_OPTIONS=log_path=/tmp/asan_log_rbusTest
-          nohup ./bin/rbusTestTimeoutValuesProvider &
-          ./bin/rbusTestTimeoutValuesConsumer || true
-          ls -lt /tmp/asan_log*
-           cat /tmp/asan_log* >> $GITHUB_STEP_SUMMARY
-     
-
-  
+          cd build/rbus
+          export ASAN_OPTIONS=log_path=/tmp/asan_log_gtest
+          nohup ./src/session_manager/rbus_session_mgr &
+          #./unittests/rbus_gtest.bin || true
+          #cd ${{github.workspace}}/rbus
+          #./address-sanitizer.sh /tmp/asan_log_gtest*
+          #second change
+          #./unittests/rbus_gtest.bin
+          #continue-on-error: true
+          #if: failure()
+           #cat /tmp/asan_log* >> $GITHUB_STEP_SUMMARY
+           #first change
+          ./unittests/rbus_gtest.bin || true
+          cat /tmp/asan_log* >> $GITHUB_STEP_SUMMARY
+      - name: Stop SessionManager
+        run: |
+          killall -9 rbus_session_mgr
       - name: Stop rtrouted
         run: |
-          killall -9 rtrouted
+          killall -9 rtrouted    
+
 
