Update valgrind-test.yml

diff --git a/.github/workflows/valgrind-test.yml b/.github/workflows/valgrind-test.yml
--- a/.github/workflows/valgrind-test.yml
+++ b/.github/workflows/valgrind-test.yml
@@ -19,23 +19,7 @@ jobs:
             build
             install
           key: ${{ runner.os }}-${{ github.sha }}
-      - name: Run tests
-        run: |
-          echo "memory leaks found"
-          exit 1  # Simulate a failure
-      
-      - name: Add Debug
-        run: |
-           echo "Repository: ${{ github.repository }}"
-           echo "Pull Request Number: ${{ github.event.pull_request.number }}"
-    
-
-
-      - name: Post comment on failure
-        if: failure()
-        run: |
-          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}comments -d '{"body": "memory leaks found\n\n${{ github.event.pull_request.body }}"}'
-
+     
       - name: Set up CMake
         # 3.16.x To support flow control commands to be overridden.
         # Installs in: find /opt -ipath *bin/cmake
@@ -44,7 +28,7 @@ jobs:
           cmake-version: '3.16.x'
       - name: Install packages
         run: >
-          sudo apt update && sudo apt install -y libcurl4-openssl-dev libgtest-dev lcov gcovr libev-dev valgrind libxml2-utils
+          sudo apt update && sudo apt install -y libcurl4-openssl-dev libgtest-dev lcov gcovr libev-dev valgrind libxml2-utils gh
       - name: Checkout rbus
         if: steps.cache.outputs.cache-hit != 'true'
         uses: actions/checkout@v3
@@ -69,6 +53,21 @@ jobs:
         if: steps.cache.outputs.cache-hit != 'true'
         run: >
           make -C build/rbus install
+      - name: Run tests
+        run: |
+          echo "memory leaks found"
+          exit 1  # Simulate a failure
+ 
+      - name: Post comment on failure
+        if: failure()
+        run: |
+          echo "Repository: ${{ github.repository }}"
+          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
+          #curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}comments -d '{"body": "memory leaks found\n\n${{ github.event.pull_request.body }}"}'
+          gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}
+          gh issue comment ${{ github.event.pull_request.number }} --body "memory ;eaks found\n\n"${{ github.event.pull_request.body }}"
+
+
       - name: Folder generation
         run: |
             mkdir -p /tmp/valgrind
