Update valgrind-test.yml

diff --git a/.github/workflows/valgrind-test.yml b/.github/workflows/valgrind-test.yml
--- a/.github/workflows/valgrind-test.yml
+++ b/.github/workflows/valgrind-test.yml
@@ -57,24 +57,80 @@ jobs:
         run: |
           echo "memory leaks found"
           exit 1  # Simulate a failure
+      - name: Post commit message comment on PR
+        uses: mshick/add-pr-comment@v2
+        with:
+          message: |
+            Pull request must be merged with a description containing the required fields,
 
-      - name: Post comment on failure
+            Summary:
+            Type: Feature/Fix/Cleanup
+            Test Plan:
+            Jira:
+
+            If there is no jira releated to this change, please put 'Jira: NO-JIRA'.
+
+            Description can be changed by editing the top comment on your pull request and making a new commit.
+      
+      # Check PR description for 'Summary:' field.
+      - name: Match 'Summary:' 
+        uses: actions-ecosystem/action-regex-match@v2
+        id: summary-match
+        if: failure() || success()
+        with:
+          text: ${{ github.event.pull_request.body }}
+          regex: 'Summary:\s*[\s\S]*?'
+          flags: gm
+
+      - name: Check 'Summary:' 
+        if: (failure() || success()) && (steps.summary-match.outputs.match == '')
+        run: exit 1
+  
+      # Check PR description for 'Type: Feature|Fix|Cleanup' field.
+      - name: Match 'Type:' 
+        uses: actions-ecosystem/action-regex-match@v2
+        id: type-match
+        if: failure() || success()
+        with:
+          text: ${{ github.event.pull_request.body }}
+          regex: 'Type:\s*Feature|Fix|Cleanup'
+
+      - name: Check 'Type:' 
+        if: (failure() || success()) && (steps.type-match.outputs.match == '')
+        run: exit 1
+        
+      # Check PR description for 'Test Plan:' field.
+      - name: Match 'Test Plan:' 
+        uses: actions-ecosystem/action-regex-match@v2
+        id: test-plan-match
+        if: failure() || success()
+        with:
+          text: ${{ github.event.pull_request.body }}
+          regex: 'Test Plan:\s*[\s\S]*?'
+
+      - name: Check 'Test Plan:' 
+        if: (failure() || success()) && (steps.test-plan-match.outputs.match == '')
+        run: exit 1
+
+      # Check PR description for 'Jira:' field.
+      - name: Match 'Jira:' 
+        uses: actions-ecosystem/action-regex-match@v2
+        id: jira-match
+        if: failure() || success()
+        with:
+          text: ${{ github.event.pull_request.body }}
+          regex: 'Jira:\s*[\s\S]*?'
+
+      - name: Check 'Jira:' 
+        if: (failure() || success()) && (steps.jira-match.outputs.match == '')
+        run: exit 1
+      
+      # Print description.
+      - name: Log string on failure
         if: failure()
-        run: |
-             echo "Repository: ${{ github.repository }}"
-             echo "Pull Request Number: 4"  # Hardcoded pull request number
-             echo "${{ secrets.GITHUB_TOKEN }}" > token.txt
-    
-             curl -sS -f -I -H "Authorization: $(cat token.txt)" https://api.github.com | grep -i x-oauth-scopes
-
-             # Post comment using hardcoded pull request number
-             RESPONSE=$(curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/123/comments -d '{"body": "memory leaks found\n\n${{ github.event.pull_request.body }}"}')
-             echo "api response : $RESPONSE"
-             gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}
-             gh issue comment 123 --body "memory leaks found\n\n${{ github.event.pull_request.body }}"
+        run: echo ${{ github.event.pull_request.body }}
 
  
-    
       - name: Folder generation
         run: |
             mkdir -p /tmp/valgrind
